---
- name: setting version variable
  vars:
    versions: {}
- set_fact:
    versions: "{{ versions | combine( { item: hostvars[item]['ansible_distribution_version'] + '_' + hostvars[item]['ansible_kernel']  } ) }}"
  with_inventory_hostnames:
    - all

- debug: msg='{{ versions }}'
- name: Dump all vars
  template:
    src: dumpall.j2
    dest: ./kernel.all    
